// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKp2qDvlJk1L8d3xhOrmzJYMr5fUH1nMU',
    appId: '1:85159378074:web:865486558e3da3f86a7323',
    messagingSenderId: '85159378074',
    projectId: 'primeform-4b8be',
    authDomain: 'primeform-4b8be.firebaseapp.com',
    storageBucket: 'primeform-4b8be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhSf_SRjj5N9pOT8uYmgxK0026gnXe7DA',
    appId: '1:85159378074:android:dcb06fc973de90be6a7323',
    messagingSenderId: '85159378074',
    projectId: 'primeform-4b8be',
    storageBucket: 'primeform-4b8be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzd5N3PEIF7booIbk4cel9royQtSpb0RA',
    appId: '1:85159378074:ios:305d1de318d979e06a7323',
    messagingSenderId: '85159378074',
    projectId: 'primeform-4b8be',
    storageBucket: 'primeform-4b8be.firebasestorage.app',
    iosBundleId: 'com.example.primeform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzd5N3PEIF7booIbk4cel9royQtSpb0RA',
    appId: '1:85159378074:ios:305d1de318d979e06a7323',
    messagingSenderId: '85159378074',
    projectId: 'primeform-4b8be',
    storageBucket: 'primeform-4b8be.firebasestorage.app',
    iosBundleId: 'com.example.primeform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKp2qDvlJk1L8d3xhOrmzJYMr5fUH1nMU',
    appId: '1:85159378074:web:b920896a42bb61916a7323',
    messagingSenderId: '85159378074',
    projectId: 'primeform-4b8be',
    authDomain: 'primeform-4b8be.firebaseapp.com',
    storageBucket: 'primeform-4b8be.firebasestorage.app',
  );
}
